name: json-validation

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  json-validation:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate JSON files
        shell: pwsh
        run: ./scripts/checks/validate-json.ps1

      - name: Check JSON Name alignment
        shell: pwsh
        run: ./scripts/checks/check-name-alignment.ps1

      - name: Check filename style
        shell: pwsh
        run: ./scripts/checks/check-filename-style.ps1
